FROM node:20-alpine

WORKDIR /app

# Instala o backend
COPY package*.json ./
RUN npm install --production

# Copia o backend
COPY . .

# Entra na pasta do frontend e faz o build
WORKDIR /app/mindmap-frontend
RUN npm install
RUN npm run build

# Copia o build para a pasta public do backend
RUN mkdir -p /app/public
RUN cp -r dist/* /app/public/

# Volta para o backend e inicia
WORKDIR /app
EXPOSE 3001
CMD ["node", "server.js"]